name: Generate tag and release
on:
  workflow_dispatch:
    inputs:
      version:
        description: New version
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  version:
    name: Create new version ${{ github.event.inputs.version }}
    runs-on: ubuntu-latest
    # Map the output from the generate_outputs job to the inputs of the release job
    outputs:
      new_tag: ${{ steps.generate_outputs.outputs.new_tag }}
      changelog: ${{ steps.generate_outputs.outputs.changelog }}
    steps:
      - uses: actions/checkout@v3
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn

      - name: Generate new version
        run: npm version ${{ github.event.inputs.version }}

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Bump WP-plugin version in work-status.php with the new NPM version
        run: |
          sed -i -e "s/Version: .*/Version: ${{ steps.package-version.outputs.current-version }}/g" work-status.php

      - name: Commit changes
        run: |
          git add .
          git commit -m "chore: bump WP-plugin version ${{ steps.package-version.outputs.current-version }}"

      - name: Push new version tag to repository
        run: git push origin main

      - name: Create branch release
        run: git checkout -b release

      - name: Build
        run: yarn build

      - name: Delete everything else than the build output folder
        run: |
          find . -maxdepth 1 ! -name 'work-status' ! -name '.git' ! -name 'package.json' ! -name '.gitignore' ! -name '.' -exec rm -rf {} +

      - name: Commit changes
        run: |
          git add .
          git commit -m "chore: release ${{ github.event.inputs.version }}"

      - name: Push new version tag to repository
        run: git push origin release --tags --force

      - name: Generate outputs
        id: generate_outputs
        run: |
          TAG_NAME=$(git describe --tags --abbrev=0)
          echo "new_tag=${TAG_NAME}" >> $GITHUB_OUTPUT
          echo "Tag name ${TAG_NAME}"

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: version
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create release notes
        uses: johnyherangi/create-release-notes@main
        id: create-release-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.version.outputs.new_tag }}
          release_name: Release ${{ needs.version.outputs.new_tag }}
          body: ${{ steps.create-release-notes.outputs.release-notes }}
